# permissions for end users to view clusterissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterissue-viewer-role
rules:
- apiGroups:
  - health.piermaster.io
  resources:
  - clusterissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - health.piermaster.io
  resources:
  - clusterissues/status
  verbs:
  - get
