---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - health.piermaster.io
  resources:
  - clusterissues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - health.piermaster.io
  resources:
  - clusterissues/finalizers
  verbs:
  - update
- apiGroups:
  - health.piermaster.io
  resources:
  - clusterissues/status
  verbs:
  - get
  - patch
  - update
